apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service-monitor
  namespace: monitoring
  labels:
    release: kube-stack 
spec:
  selector:
    matchLabels:
      app: auth-service 
  namespaceSelector:
    matchNames:
      - default 
  endpoints:
  - port: http 
    path: /api/v1/auth/metrics
    interval: 15s