apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb://host.docker.internal:27018/taskflow-auth"
  REDIS_URI: "redis://host.docker.internal:6380"
  JWT_ACCESS_SECRET: "your_super_secret_access_key_12345"
  JWT_REFRESH_SECRET: "your_super_secret_refresh_key_67890"