apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb://host.docker.internal:27018/taskflow-notification"
  REDIS_URI: "redis://host.docker.internal:6382"
  JWT_SECRET: "your_super_secret_access_key_12345"